name: Retrieve Repository, Branch, and Run ID

on: [push, pull_request]

jobs:
  get-info:
    runs-on: ubuntu-latest

    steps:
      - name: Extract repository name
        run: |
          echo "repository-name=$(basename $(git rev-parse --show-toplevel))"
          echo "##[set-output name=repository-name;]$repository-name"
        id: extract-repository-name

      - name: Extract current branch
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "##[set-output name=branch;]$branch"
        id: extract-branch-name

      - name: Extract run ID
        run: |
          run-id=$(echo ${{ github.run_id }})
          echo "##[set-output name=run-id;]$run-id"
        id: extract-run-id

      - name: Replace '/' with '-' in repository name
        run: |
          current-repo-name=$(echo "${{ steps.extract-repository-name.outputs.repository-name }}")
          replaced-repo-name=$(echo $current-repo-name | sed "s/\//-/g")
          echo "##[set-output name=replaced-repo-name;]$replaced-repo-name"
        id: replace-repo-name

      - name: Concatenation of repository, branch, and run ID
        run: |
          replaced-repo-name=$(echo "${{ steps.replaced-repo-name.outputs.replaced-repo-name }}")
          current-branch=$(echo "${{ steps.extract-branch-name.outputs.branch }}")
          run-id=$(echo "${{ steps.extract-run-id.outputs.run-id }}")
          concated-value="$replaced-repo-name/$current-branch/$run-id"
          echo $concated-value
